### PR TITLE
citation v0.3.0 update

### PR DESCRIPTION
**Pull request by mosesyhc**

### CODE REVIEW

**Comment by kylegodbey** [comment]
Should this line:

`BAND SDK v0.2 Community Policies`

be updated? or are the community policies v0.2?

**Comment by mosesyhc** [comment]
> Should this line:
> 
> `BAND SDK v0.2 Community Policies`
> 
> be updated? or are the community policies v0.2?

Did the SDK change? I assume if the SDK did not change, its version does not. @wildsm, thoughts?

**Comment by wildsm** [comment]
Correct, SDK still at v0.2: https://github.com/bandframework/bandframework/blob/main/resources/sdkpolicies/bandsdk.md

It was coincidence that the numbers aligned for BAND v0.2.

**Review by furnstahl — APPROVED** [review]
This is fine.

**Comment by wildsm** [comment]
I added parmoo just now

**Pull request merged**
