### PR TITLE
Updating some things to reflect v0.3.0

### PR DESCRIPTION
**Pull request by wildsm**

### CODE REVIEW

**Comment by wildsm** [comment]
Here are the things I thought needed to be updated. Anything else @furnstahl & @DanielRPhillips & others?

**Comment by furnstahl** [comment]
Looks good to me.

**Comment by DanielRPhillips** [comment]
Looks good to me too. I have added a news item about your INFORMS prize Stefan. (Something I've been meaning to do for ten days but finally got around to today.)

**Review by DanielRPhillips — COMMENTED** [review]
This looks good, but will need to be merged with my simultaneous addition of a news item.

**Pull request merged**
