### PR TITLE
Include news item for retreat and advisory board meeting

### PR DESCRIPTION
**Pull request by mosesyhc**
A news item is written up for the annual retreat and advisory board meeting.  Feel free to edit / invite other reviewers.

### CODE REVIEW

**Review by DanielRPhillips — DISMISSED** [review]
I think I may've hit this button too quickly last time. :) 

This looks great. Thank you for doing it @mosesyhc . My only suggestion is to change the tense (and maybe the verbs) in the second sentence to: "During the retreat, BAND members  gathered to review..."

**Review by DanielRPhillips — APPROVED** [review]

**Comment by DanielRPhillips** [comment]
Looks good to me now @mosesyhc

**Comment by DanielRPhillips** [comment]
Looks good to me now, @mosesyhc

**Comment by ozgesurer** [comment]
Looks great @mosesyhc

**Review by ozgesurer — APPROVED** [review]

**Pull request merged**
